FROM registry.access.redhat.com/ubi8/nodejs-14 as build
# Install dependencies
COPY package.json package-lock.json  /opt/app-root/src/
RUN npm ci --no-optional
# Copy app
COPY . /opt/app-root/src/
# Build
RUN npm run build


FROM registry.access.redhat.com/ubi8/nginx-118
# Get build folder
COPY --from=build /opt/app-root/src/build .

# Add config
COPY nginx.conf "${NGINX_CONF_PATH}"

# Run script uses standard ways to run the application
CMD nginx -g "daemon off;"
