FROM registry.access.redhat.com/ubi8/nodejs-12

# Copy and cache dependencies
COPY package.json package-lock.json ./
RUN npm ci --production

# Copy and cache source
COPY source ./source
COPY app.js .

EXPOSE 8080

CMD npm start
