version: '3'
services:
  exchange:
    build:
      context: ../../exchange
      dockerfile: Containerfile
    ports:
    - "8080:8080"
    depends_on:
    - currency
    - history
    - news
  currency:
    build:
      context: ../../currency
      dockerfile: Containerfile
    ports:
    - "8081:5000"
  history:
    build:
      context: ../../history
      dockerfile: Containerfile
    ports:
    - "8082:8080"
