#!/usr/bin/env bash

# Set the current working directory
cd $(dirname $0)

Use podman-compose if available
if [ -x "$(command -v podman-compose)" ]
then
    COMPOSE="podman-compose"
else
    COMPOSE="docker-compose"
fi

COMPOSE="docker-compose"

$COMPOSE -f local-services.yml up