FROM registry.redhat.io/openshift4/ose-jenkins-agent-base:v4.6

# Add repos
COPY CentOS.repo /etc/yum.repos.d/
RUN yum install -y --setopt=tsflags=nodocs gcc-c++ make
RUN curl -sL https://rpm.nodesource.com/setup_12.x | bash -

# Reference: https://github.com/cypress-io/cypress-docker-images/blob/master/base/centos7-12.4.0/Dockerfile
RUN yum install -y --disableplugin=subscription-manager --setopt=tsflags=nodocs \
        nodejs xorg-x11-server-Xvfb gtk2-devel gtk3-devel libnotify-devel GConf2 nss libXScrnSaver alsa-lib && \
    yum clean all -y && \
    rm -rf /var/cache/yum && \
    npm install --unsafe-perm -g npm-audit-html npm-audit-ci-wrapper sonar-scanner || cat /home/jenkins/.npm/_logs/*-debug.log && \
    chown root:root /home/jenkins -R && \
    chmod 775 /home/jenkins/.config -R && \
    chmod 775 /home/jenkins/.npm -R

USER 1001
