FROM registry.redhat.io/openshift4/ose-jenkins-agent-base

RUN python -m pip install --user -U pip && \
    chown root:root /home/jenkins -R && \
    chmod 775 /home/jenkins/.local -R

# Local pip installation path
ENV PATH ${PATH}:/home/jenkins/.local/bin

# Fix UnicodeDecodeError
ENV LC_ALL=en_US.UTF-8

USER 1001

